# Generated by Django 2.2.3 on 2019-07-05 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default='')),
                ('end_date', models.DateField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('file_name', models.CharField(default='', max_length=200)),
                ('file_mime', models.CharField(default='', max_length=100)),
                ('file_content', models.TextField(default='')),
                ('experiment_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_v1.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsing_datetime', models.DateTimeField(auto_now=True)),
                ('parsing_method', models.CharField(default='', max_length=50)),
                ('data', models.TextField(default='')),
                ('experiment_file_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_v1.ExperimentFile')),
            ],
        ),
    ]
