# Generated by Django 2.2.3 on 2019-07-04 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='end_date',
            field=models.DateField(blank=True, default=models.DateField(null=True)),
        ),
        migrations.AddField(
            model_name='experiment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experiment',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='experiment_file_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_v1.ExperimentFile'),
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='parsing_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='experimentdata',
            name='parsing_method',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='experiment_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='api_v1.Experiment'),
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='file_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='file_mime',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='file_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='experimentfile',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
