# Generated by Django 2.2.3 on 2019-07-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='experimentdata',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='experimentfile',
            options={'ordering': ['-id']},
        ),
    ]
