# Generated by Django 2.2.3 on 2019-07-05 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentdata',
            old_name='experiment_file_id',
            new_name='experiment_file',
        ),
        migrations.RenameField(
            model_name='experimentfile',
            old_name='experiment_id',
            new_name='experiment',
        ),
    ]
