# Generated by Django 2.2.3 on 2019-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_auto_20190705_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentdata',
            name='data',
            field=models.TextField(choices=[('JSON', 'json parser'), ('PLAIN', 'plaintext parser'), ('XML', 'xml parser')], default=''),
        ),
    ]
